# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcloud < Formula
  desc ""
  homepage "https://github.com/moovit-sp-gmbh/hcloud-api-client"
  version "0.0.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/0.0.21/hcloud_0.0.21_darwin_amd64.tar.gz"
      sha256 "76a69fa4ebf3cae71bed7bae34e45c4276c7182246555968c480f0fdac545af9"

      def install
        bin.install "hcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/0.0.21/hcloud_0.0.21_darwin_arm64.tar.gz"
      sha256 "d8c4b1936cd8cc5d9f8b9979e70ea714223c1afd6983752acfdbca4c9341b5bf"

      def install
        bin.install "hcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/0.0.21/hcloud_0.0.21_linux_arm64.tar.gz"
      sha256 "544cbd747aec9088bf95831a103a0a432e3575cb32558d67e6681de139760ba8"

      def install
        bin.install "hcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/0.0.21/hcloud_0.0.21_linux_amd64.tar.gz"
      sha256 "c2710b2357ddd5c4e9216901fe204ca9cfd2b4b1a0ca998d363e5c805b39d45b"

      def install
        bin.install "hcloud"
      end
    end
  end
end
